import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Layout/Navbar";
import Footer from "@/Components/Layout/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

 const poppins = Poppins({
weight:["100","200","300","400","500","600","700","800"]
});



export const metadata = {
  title: "Care-xyz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className}  antialiased`}>
          <header className="py-2 md:w-11/12 mx-auto">
            <Navbar></Navbar>
          </header>
          <main className="py-2 md:w-11/12 mx-auto">{children}</main>
          <footer className="py-2 md:w-11/12 mx-auto">
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </NextAuthProvider>
  )
}
